replicaCount: 2

image:
  repository: ghcr.io/wdzysm/vultr-k8s-demo
  pullPolicy: Always
  tag: latest

nameOverride: ""
fullnameOverride: ""

env:
  - name: JAVA_TOOL_OPTIONS
    value: -Djava.net.preferIPv4Stack=true -Dspring.output.ansi.enabled=always -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
  - name: SPRING_HAZELCAST_CONFIG
    value: classpath:hazelcast/hazelcast-kubernetes.yaml

service:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: hazelcast
      port: 5701
      targetPort: 5701

ports:
  - name: http
    containerPort: 80
    protocol: TCP
  - name: hazelcast
    containerPort: 5701
    protocol: TCP

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 5
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 5

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
