on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
      - uses: gradle/gradle-build-action@v2
      - run: |
          echo "${{ secrets.GITOPS_TOKEN }}" | docker login ghcr.io -u wdzysm --password-stdin
          ./gradlew jib -Djib.from.image=eclipse-temurin:8u332-b09-jdk-alpine -Djib.to.image=ghcr.io/wdzysm/vultr-k8s-demo --console=plain --info